services:
  but-does-it-fly:
    container_name: but-does-it-fly
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USERNAME=default
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ../:/workspace:cached
    environment:
      - USERNAME=default
      - UID=${UID}
      - GID=${GID}
      #- CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc