[package]
name = "safety-lights"
version = "0.1.0"
edition = "2024"

[dependencies]
communication-protocol = { path = "../protocol" }
gpio-lights = { path = "../gpio_lights" }
futures = "0.3"
rppal = "0.22.1"
tokio = { version = "1", features = ["macros", "rt", "signal", "sync", "time"] }
tokio-util = "0.7"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
expect_used = "deny"
panic = "deny"
unwrap_used = "deny"
todo = "deny"
unimplemented = "deny"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
